import {TeamName, Teams} from "../types";

export const TEAMS: Teams = {
    [TeamName.Pastoral]: [
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Pastor',
            team: TeamName.Pastoral,
            email: 'gerargchimb@gmail.com',
            description: 'Main Pastor',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Associate Pastor',
        }
    ],
    [TeamName.Administration]: [
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
    ],
    [TeamName.Elders]: [
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Elders,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Elders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Elders,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Elders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
    ],
    [TeamName.Deacons]: [
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Moses Ufumeli',
            title: 'Secretary',
            team: TeamName.Deacons,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Manages church records and administrative operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/jonah.jpg`,
            name: 'Jonah Mudehwe',
            title: 'Board Member',
            team: TeamName.Deacons,
            email: 'mudehwes@yahoo.co.uk',
            description: 'Oversees church policies and financial decisions.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Deacons,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Deacons,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Deacons,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Deacons,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
    ],
    [TeamName.Cell_Leaders]: [
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Cell Group Leader',
            team: TeamName.Cell_Leaders,
            email: 'johndoe@example.com',
            description: 'Facilitates small group Bible studies and discipleship meetings.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Moses Ufumeli',
            title: 'Cell Group Leader',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Provides guidance and support to small group members.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Cell_Leaders,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Cell_Leaders,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/gerard.jpg`,
            name: 'Gerard Chimbganda',
            title: 'Senior Pastor',
            team: TeamName.Cell_Leaders,
            email: 'johndoe@example.com',
            description: 'Leads the congregation in spiritual growth, provides counseling, and oversees church operations.',
        },
        {
            image: `${process.env.PUBLIC_URL}/assets/moses.jpg`,
            name: 'Alex Kadonzvo',
            title: 'Associate Pastor',
            team: TeamName.Cell_Leaders,
            email: 'ufumelims@yahoo.co.uk',
            description: 'Leads the worship team, organizes praise sessions, and ensures a vibrant worship experience.',
        },
    ],

};